### ISSUE TITLE
Server issues when going back one page and then going forward

### ISSUE THREAD

**Issue by VitorJeronimo** [VitorJeronimo/CSCI3428_Eskasoni_Project#5]
If a user logs in,  goes back one page and then goes forward one page the server will crash.

Probably because they will be allowed to return to the game page without providing an username and room ID, so that info will be null in the server.

We should write something to catch that null entry, or save the user's info in the local storage or something similar.

**Comment by Gillyweed** [comment]
I can look into this tonight after work, how is the rest of the
merging going?

**Comment by VitorJeronimo** [comment]
Going pretty well. I got rid of a bunch of unnecessary code and fixed a few things.

The server is fully documented and I might just clean a couple of functions on App.js today and that's it.
